// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/installation-team-editor/Current.tsx": () => import("../components/mockups/installation-team-editor/Current.tsx"),
  "./components/mockups/installation-team-editor/Inline.tsx": () => import("../components/mockups/installation-team-editor/Inline.tsx"),
  "./components/mockups/quotation-request-row/Compact.tsx": () => import("../components/mockups/quotation-request-row/Compact.tsx"),
  "./components/mockups/quotation-request-row/Current.tsx": () => import("../components/mockups/quotation-request-row/Current.tsx")
};
