import { Link } from 'wouter';
import { ArrowUpRight, CheckCircle2, CircleAlert, Eye, Pencil, ShieldCheck, UsersRound } from 'lucide-react';
import { getGetAdminSummaryQueryKey, getGetDashboardQueryKey, useGetAdminSummary, useGetDashboard } from '@workspace/api-client-react';
import type { User } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { MODULES } from '@/lib/modules';

function LoadingDashboard() {
  return <div className="space-y-6"><div className="h-32 animate-pulse rounded-2xl bg-card/80" /><div className="grid gap-4 md:grid-cols-3"><div className="h-28 animate-pulse rounded-2xl bg-card/80" /><div className="h-28 animate-pulse rounded-2xl bg-card/80" /><div className="h-28 animate-pulse rounded-2xl bg-card/80" /></div></div>;
}

export default function DashboardPage({ user }: { user: User }) {
  const isMasterAdmin = user.roleId === 'master-admin';
  const dashboard = useGetDashboard({ query: { queryKey: getGetDashboardQueryKey() } });
  const summary = useGetAdminSummary({ query: { enabled: isMasterAdmin, queryKey: getGetAdminSummaryQueryKey() } });
  const permittedModules = MODULES.filter((module) => user.permissions?.[module.key] === 'view' || user.permissions?.[module.key] === 'edit');
  const retry = () => {
    void dashboard.refetch();
    if (isMasterAdmin) void summary.refetch();
  };
  const dashboardLoading = dashboard.isLoading || (isMasterAdmin && summary.isLoading);
  const dashboardError = dashboard.isError || (isMasterAdmin && summary.isError);

  return <AppShell user={user} title="Operations dashboard" eyebrow="Today at a glance">
    {dashboardLoading ? <LoadingDashboard /> : dashboardError ? <div className="flex min-h-[420px] items-center justify-center"><div className="max-w-sm rounded-2xl border border-destructive/20 bg-card p-7 text-center"><CircleAlert className="mx-auto text-destructive" size={28} /><h2 className="mt-4 font-display text-lg font-bold">Dashboard unavailable</h2><p className="mt-2 text-sm text-muted-foreground">We couldn't load the latest workspace summary.</p><button onClick={retry} className="mt-5 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground" data-testid="button-retry-dashboard">Try again</button></div></div> : <div className="space-y-6">
      <section className="animate-enter-up relative overflow-hidden rounded-2xl bg-sidebar p-6 text-sidebar-foreground shadow-sm md:p-8"><div className="absolute -right-8 -top-16 h-56 w-56 rounded-full border border-sidebar-primary/20" /><div className="absolute right-12 top-10 h-24 w-24 rounded-full border border-sidebar-primary/15" /><div className="relative max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sidebar-primary">Welcome back, {dashboard.data?.userName || user.name.split(' ')[0]}</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-0.04em] md:text-4xl">{isMasterAdmin ? 'Keep the whole floor moving.' : 'Your work, clearly in view.'}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-sidebar-foreground/60">Your access is set up for the {dashboard.data?.roleLabel || user.roleName} workspace. You can see the modules assigned to your role below.</p>{isMasterAdmin && <div className="mt-6 flex flex-wrap gap-3"><Link href="/admin/users" className="inline-flex items-center gap-2 rounded-lg bg-sidebar-primary px-4 py-2.5 text-xs font-bold text-sidebar-primary-foreground" data-testid="link-dashboard-users">Manage users <ArrowUpRight size={14} /></Link><Link href="/admin/roles" className="inline-flex items-center gap-2 rounded-lg border border-sidebar-border px-4 py-2.5 text-xs font-semibold text-sidebar-foreground hover:bg-sidebar-accent" data-testid="link-dashboard-roles">Review roles</Link></div>}</div></section>
      {isMasterAdmin ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="animate-enter-up delay-1 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Active users</p><UsersRound size={17} className="text-primary" /></div><p className="mt-4 font-display text-3xl font-bold" data-testid="metric-active-users">{summary.data?.activeUsers ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">{summary.data?.inactiveUsers ?? 0} inactive account{summary.data?.inactiveUsers === 1 ? '' : 's'}</p></div>
        <div className="animate-enter-up delay-2 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Custom roles</p><ShieldCheck size={17} className="text-primary" /></div><p className="mt-4 font-display text-3xl font-bold" data-testid="metric-total-roles">{summary.data?.totalRoles ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">{summary.data?.masterAdmins ?? 0} master admin{summary.data?.masterAdmins === 1 ? '' : 's'}</p></div>
        <div className="animate-enter-up delay-3 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Total accounts</p><CheckCircle2 size={17} className="text-primary" /></div><p className="mt-4 font-display text-3xl font-bold" data-testid="metric-total-users">{summary.data?.totalUsers ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">Across all teams</p></div>
        <div className="animate-enter-up delay-4 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Modules</p><span className="font-display text-xs font-bold text-accent-foreground">01 / 14</span></div><p className="mt-4 font-display text-3xl font-bold" data-testid="metric-module-count">{dashboard.data?.moduleCount ?? MODULES.length}</p><p className="mt-1 text-xs text-muted-foreground">Module 1 available now</p></div>
      </section> : <section className="grid gap-4 sm:grid-cols-3">
        <div className="animate-enter-up delay-1 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Permitted modules</p><ShieldCheck size={17} className="text-primary" /></div><p className="mt-4 font-display text-3xl font-bold" data-testid="metric-permitted-modules">{dashboard.data?.moduleCount ?? permittedModules.length}</p><p className="mt-1 text-xs text-muted-foreground">Assigned to your role</p></div>
        <div className="animate-enter-up delay-2 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Role profile</p><UsersRound size={17} className="text-primary" /></div><p className="mt-4 truncate font-display text-xl font-bold" data-testid="metric-role-label">{dashboard.data?.roleLabel || user.roleName}</p><p className="mt-1 text-xs text-muted-foreground">Your current access template</p></div>
        <div className="animate-enter-up delay-3 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Access scope</p><Pencil size={17} className="text-primary" /></div><p className="mt-4 font-display text-xl font-bold" data-testid="metric-access-scope">{permittedModules.filter((module) => user.permissions?.[module.key] === 'edit').length} editable</p><p className="mt-1 text-xs text-muted-foreground">View and edit combined</p></div>
      </section>}
      <section className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
        <div className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">{isMasterAdmin ? 'Workspace map' : 'Your access'}</p><h2 className="mt-2 font-display text-xl font-bold">{isMasterAdmin ? 'Your 14-module workspace' : 'Modules assigned to you'}</h2></div><span className="rounded-full bg-secondary px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-secondary-foreground">{isMasterAdmin ? '1 active' : `${permittedModules.length} allowed`}</span></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{(isMasterAdmin ? MODULES : permittedModules).map((module) => <div key={module.key} className={`flex items-center gap-3 rounded-xl border px-3 py-3 ${module.built ? 'border-primary/25 bg-primary/5' : 'border-border/70 bg-muted/30'}`} data-testid={`module-status-${module.key}`}><span className={`grid h-7 w-7 place-items-center rounded-lg text-[10px] font-bold ${module.built ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{module.built ? '01' : '—'}</span><div className="min-w-0 flex-1"><p className={`text-xs font-semibold ${module.built ? 'text-foreground' : 'text-muted-foreground'}`}>{module.label}</p><p className="text-[10px] text-muted-foreground">{module.built ? 'Available' : isMasterAdmin ? 'Coming Soon' : user.permissions?.[module.key] === 'edit' ? 'Edit access · Coming Soon' : 'View access · Coming Soon'}</p></div>{!isMasterAdmin && (user.permissions?.[module.key] === 'edit' ? <Pencil size={13} className="text-primary" /> : <Eye size={13} className="text-muted-foreground" />)}</div>)}</div>{!isMasterAdmin && permittedModules.length === 0 && <div className="mt-4 rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted-foreground">No modules are assigned to this role yet.</div>}</div>
        {isMasterAdmin ? <div className="rounded-2xl border border-border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Admin checklist</p><h2 className="mt-2 font-display text-xl font-bold">Access, made explicit.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Set up the people and permission templates your office and factory teams need before orders go live.</p><div className="mt-6 space-y-3"><Link href="/admin/users" className="group flex items-center justify-between rounded-xl border border-border p-3 hover:border-primary/40" data-testid="link-checklist-users"><span className="flex items-center gap-3 text-xs font-semibold"><UsersRound size={16} className="text-primary" /> Add or edit staff</span><ArrowUpRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-0.5" /></Link><Link href="/admin/roles" className="group flex items-center justify-between rounded-xl border border-border p-3 hover:border-primary/40" data-testid="link-checklist-roles"><span className="flex items-center gap-3 text-xs font-semibold"><ShieldCheck size={16} className="text-primary" /> Define role templates</span><ArrowUpRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-0.5" /></Link></div></div> : <div className="rounded-2xl border border-border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Role overview</p><h2 className="mt-2 font-display text-xl font-bold">{dashboard.data?.roleLabel || user.roleName}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Your dashboard stays focused on the workspaces your role can access. Modules marked view are read-only; edit access allows updates when the module is released.</p><div className="mt-6 flex items-center gap-3 rounded-xl bg-secondary/60 p-4"><div className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-secondary-foreground"><ShieldCheck size={17} /></div><div><p className="text-xs font-bold">Permission-aware workspace</p><p className="mt-1 text-[11px] text-muted-foreground">{dashboard.data?.moduleCount ?? permittedModules.length} module{(dashboard.data?.moduleCount ?? permittedModules.length) === 1 ? '' : 's'} currently assigned</p></div></div></div>}
      </section>
    </div>}
  </AppShell>;
}